export const LOADER_ACTION = "LOADER_ACTION";
export const STOP_LOADER = "STOP_LOADER";
export const SET_USER = "SET_USER";
export const SET_ADMIN = "SET_ADMIN";
export const REMOVE_USER = "REMOVE_USER";
export const SET_AIRTABLE_DATA = "SET_AIRTABLE_DATA";
export const SET_EXPENSE_DATA = "SET_EXPENSE_DATA";
export const SET_BOARDS = "SET_BOARDS";

export const SET_LISTS = "SET_LISTS";
export const SET_NEW_LISTS = "SET_NEW_LISTS";
export const SET_ALL_LISTS = "SET_ALL_LISTS";
export const SET_CARDS = "SET_CARDS";
export const SET_CANVAS_LISTS = "SET_CANVAS_LISTS";
export const SET_CANVAS_CARDS = "SET_CANVAS_CARDS";
export const SET_MILESTONE_LISTS = "SET_MILESTONE_LISTS";
export const SET_MILESTONE_CARDS = "SET_MILESTONE_CARDS";
export const SET_BLOGS = "SET_BLOGS";
export const SET_CANVAS = "SET_CANVAS";
export const SET_MILESTONES = "SET_MILESTONES";
export const DELETE_CARD = "DELETE_CARD";
export const DELETE_LIST = "DELETE_LIST";
export const SET_ADMIN_METRICS_DATA = "SET_ADMIN_METRICS_DATA";

export const SET_ADMIN_USER = "SET_ADMIN_USER";
export const SET_ADMIN_BOARDS = "SET_ADMIN_BOARDS";
export const SET_ADMIN_LISTS = "SET_ADMIN_LISTS";
export const SET_ADMIN_CARDS = "SET_ADMIN_CARDS";

export const DRAG_WITHIN_LIST = "DRAG_WITHIN_LIST";
export const DRAG_ACROSS_LIST = "DRAG_ACROSS_LIST";

export const SET_VALUE = "SET_VALUE";
export const SET_TEAMS_VALUE = "SET_TEAMS_VALUE";
export const SET_VISION_VALUE = "SET_VISION_VALUE";
export const SET_PROPOSITION_VALUE = "SET_PROPOSITION_VALUE";
export const SET_PRODUCT_VALUE = "SET_PRODUCT_VALUE";
export const SET_MARKET_VALUE = "SET_MARKET_VALUE";
export const SET_BUSINESS_VALUE = "SET_BUSINESS_VALUE";
export const SET_INVESTMENT_VALUE = "SET_INVESTMENT_VALUE";

export const SET_STATEMENTS = "SET_STATEMENTS";
export const SET_OBJECTIVES = "SET_OBJECTIVES";
export const SET_NOTES = "SET_NOTES";
export const SET_NOTE = "SET_NOTE";
export const SET_ALL_OBJECTIVES = "SET_ALL_OBJECTIVES";

export const SET_ADMIN_STATEMENTS = "SET_ADMIN_STATEMENTS";
export const SET_ADMIN_OBJECTIVES = "SET_ADMIN_OBJECTIVES";
export const SET_ADMIN_VALUES = "SET_ADMIN_VALUES";

export const SET_USER_ACTIVITY = "SET_USER_ACTIVITY";

export const SET_LOANS = "SET_LOANS";
export const SET_RB_LOANS = "SET_RB_LOANS";

export const SET_REVSHARE = "SET_REVSHARE";

export const SET_AUTHOR = "SET_AUTHOR";

export const SET_REVENUE = "SET_REVENUE";
export const SET_OUTSTANDING_REVSHARE_PAYMENT =
  "SET_OUTSTANDING_REVSHARE_PAYMENT";

export const SET_REVENUE_TRACKING = "SET_REVENUE_TRACKING";
export const SET_REVENUE_ACCUMULATION = "SET_REVENUE_ACCUMULATION";

export const SET_FEATURES = "SET_FEATURES";

export const SET_ALL_USERS = "SET_ALL_USERS";

export const SET_DIAGNOSTICS_PAYLOAD = "SET_DIAGNOSTICS_PAYLOAD";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_DIAGNOSTICS = "SET_DIAGNOSTICS";

export const SET_DIAGNOSTICS_TOOLS = "SET_DIAGNOSTICS_TOOLS";

export const SET_PROFILE = "SET_PROFILE";
export const SET_ALL_PROFILES = "SET_ALL_PROFILES";

export const SET_CURRENT_QUARTER = "SET_CURRENT_QUARTER";

export const SET_PROGRAMS = "SET_PROGRAMS";

export const SET_MENTOR = "SET_MENTOR";

export const SET_EVENTS = "SET_EVENTS";
