export const LOADER_ACTION = 'LOADER_ACTION'
export const STOP_LOADER = 'STOP_LOADER'
export const SET_USER = 'SET_USER'
export const SET_ADMIN = 'SET_ADMIN'
export const REMOVE_USER = 'REMOVE_USER'
export const SET_AIRTABLE_DATA = 'SET_AIRTABLE_DATA'
export const SET_EXPENSE_DATA = 'SET_EXPENSE_DATA'
export const SET_BOARDS = 'SET_BOARDS'
export const SET_LISTS = 'SET_LISTS'
export const SET_NEW_LISTS = 'SET_NEW_LISTS'
export const SET_ALL_LISTS = 'SET_ALL_LISTS'
export const SET_CARDS = 'SET_CARDS'
export const SET_CANVAS_LISTS = 'SET_CANVAS_LISTS'
export const SET_CANVAS_CARDS = 'SET_CANVAS_CARDS'
export const SET_MILESTONE_LISTS = 'SET_MILESTONE_LISTS'
export const SET_MILESTONE_CARDS = 'SET_MILESTONE_CARDS'
export const SET_BLOGS = 'SET_BLOGS'
export const SET_CANVAS = 'SET_CANVAS'
export const SET_MILESTONES = 'SET_MILESTONES'
export const DELETE_CARD = 'DELETE_CARD'
export const DELETE_LIST = 'DELETE_LIST'
export const SET_METRICS_DATA = 'SET_METRICS_DATA'
export const SET_ADMIN_METRICS_DATA = 'SET_ADMIN_METRICS_DATA'

export const SET_ADMIN_USER = 'SET_ADMIN_USER'
export const SET_ADMIN_BOARDS = 'SET_ADMIN_BOARDS'
export const SET_ADMIN_LISTS = 'SET_ADMIN_LISTS'
export const SET_ADMIN_CARDS = 'SET_ADMIN_CARDS'

export const DRAG_WITHIN_LIST = 'DRAG_WITHIN_LIST'
export const DRAG_ACROSS_LIST = 'DRAG_ACROSS_LIST'

export const SET_VALUE = 'SET_VALUE'
export const SET_TEAMS_VALUE = 'SET_TEAMS_VALUE'
export const SET_VISION_VALUE = 'SET_VISION_VALUE'
export const SET_PROPOSITION_VALUE = 'SET_PROPOSITION_VALUE'
export const SET_PRODUCT_VALUE = 'SET_PRODUCT_VALUE'
export const SET_MARKET_VALUE = 'SET_MARKET_VALUE'
export const SET_BUSINESS_VALUE = 'SET_BUSINESS_VALUE'
export const SET_INVESTMENT_VALUE = 'SET_INVESTMENT_VALUE'

export const SET_STATEMENTS = 'SET_STATEMENTS'
export const SET_OBJECTIVES = 'SET_OBJECTIVES'

export const SET_ADMIN_STATEMENTS = 'SET_ADMIN_STATEMENTS'
export const SET_ADMIN_OBJECTIVES = 'SET_ADMIN_OBJECTIVES'

export const SET_USER_ACTIVITY = "SET_USER_ACTIVITY"

export const SET_LOANS = "SET_LOANS"

export const SET_REVSHARE = "SET_REVSHARE"